obj-$(CONFIG_VPU_SEP0611) += hx170dec.o
obj-$(CONFIG_VPU_SEP0611) += memalloc.o






#obj-m += hx170dec.o  
#obj-m += memalloc.o
#KERNELDIR ?=/opt/0208/Linux/DDR2_Demo/kernel



 
#PWD       := $(shell pwd)

#default:
#	$(MAKE) -C $(KERNELDIR) M=$(PWD)  modules

#clean:
#	rm -f *.ko *.o *.mod.c *.order *.symvers
