#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define TSK_ACTIVE_MM 224 /* offsetof(struct task_struct, active_mm)	@ */

#define TI_FLAGS 0 /* offsetof(struct thread_info, flags)	@ */
#define TI_PREEMPT 4 /* offsetof(struct thread_info, preempt_count)	@ */
#define TI_ADDR_LIMIT 8 /* offsetof(struct thread_info, addr_limit)	@ */
#define TI_TASK 12 /* offsetof(struct thread_info, task)	@ */
#define TI_EXEC_DOMAIN 16 /* offsetof(struct thread_info, exec_domain)	@ */
#define TI_CPU 20 /* offsetof(struct thread_info, cpu)	@ */
#define TI_CPU_SAVE 24 /* offsetof(struct thread_info, cpu_context)	@ */
#define TI_USED_CP 132 /* offsetof(struct thread_info, used_cp)	@ */
#define TI_FPSTATE 152 /* offsetof(struct thread_info, fpstate)	@ */

#define S_R0 0 /* offsetof(struct pt_regs, UCreg_00)	@ */
#define S_R1 4 /* offsetof(struct pt_regs, UCreg_01)	@ */
#define S_R2 8 /* offsetof(struct pt_regs, UCreg_02)	@ */
#define S_R3 12 /* offsetof(struct pt_regs, UCreg_03)	@ */
#define S_R4 16 /* offsetof(struct pt_regs, UCreg_04)	@ */
#define S_R5 20 /* offsetof(struct pt_regs, UCreg_05)	@ */
#define S_R6 24 /* offsetof(struct pt_regs, UCreg_06)	@ */
#define S_R7 28 /* offsetof(struct pt_regs, UCreg_07)	@ */
#define S_R8 32 /* offsetof(struct pt_regs, UCreg_08)	@ */
#define S_R9 36 /* offsetof(struct pt_regs, UCreg_09)	@ */
#define S_R10 40 /* offsetof(struct pt_regs, UCreg_10)	@ */
#define S_R11 44 /* offsetof(struct pt_regs, UCreg_11)	@ */
#define S_R12 48 /* offsetof(struct pt_regs, UCreg_12)	@ */
#define S_R13 52 /* offsetof(struct pt_regs, UCreg_13)	@ */
#define S_R14 56 /* offsetof(struct pt_regs, UCreg_14)	@ */
#define S_R15 60 /* offsetof(struct pt_regs, UCreg_15)	@ */
#define S_R16 64 /* offsetof(struct pt_regs, UCreg_16)	@ */
#define S_R17 68 /* offsetof(struct pt_regs, UCreg_17)	@ */
#define S_R18 72 /* offsetof(struct pt_regs, UCreg_18)	@ */
#define S_R19 76 /* offsetof(struct pt_regs, UCreg_19)	@ */
#define S_R20 80 /* offsetof(struct pt_regs, UCreg_20)	@ */
#define S_R21 84 /* offsetof(struct pt_regs, UCreg_21)	@ */
#define S_R22 88 /* offsetof(struct pt_regs, UCreg_22)	@ */
#define S_R23 92 /* offsetof(struct pt_regs, UCreg_23)	@ */
#define S_R24 96 /* offsetof(struct pt_regs, UCreg_24)	@ */
#define S_R25 100 /* offsetof(struct pt_regs, UCreg_25)	@ */
#define S_R26 104 /* offsetof(struct pt_regs, UCreg_26)	@ */
#define S_FP 108 /* offsetof(struct pt_regs, UCreg_fp)	@ */
#define S_IP 112 /* offsetof(struct pt_regs, UCreg_ip)	@ */
#define S_SP 116 /* offsetof(struct pt_regs, UCreg_sp)	@ */
#define S_LR 120 /* offsetof(struct pt_regs, UCreg_lr)	@ */
#define S_PC 124 /* offsetof(struct pt_regs, UCreg_pc)	@ */
#define S_PSR 128 /* offsetof(struct pt_regs, UCreg_csr)	@ */
#define S_OLD_R0 132 /* offsetof(struct pt_regs, UCreg_ORIG_00)	@ */
#define S_FRAME_SIZE 136 /* sizeof(struct pt_regs)	@ */

#define VMA_VM_MM 0 /* offsetof(struct vm_area_struct, vm_mm)	@ */
#define VMA_VM_FLAGS 20 /* offsetof(struct vm_area_struct, vm_flags)	@ */

#define VM_EXEC 4 /* VM_EXEC	@ */

#define PAGE_SZ 4096 /* PAGE_SIZE	@ */

#define SYS_ERROR0 10420224 /* 0x9f0000	@ */

#define SIZEOF_MACHINE_DESC 52 /* sizeof(struct machine_desc)	@ */
#define MACHINFO_TYPE 0 /* offsetof(struct machine_desc, nr)	@ */
#define MACHINFO_NAME 12 /* offsetof(struct machine_desc, name)	@ */
#define MACHINFO_PHYSIO 4 /* offsetof(struct machine_desc, phys_io)	@ */
#define MACHINFO_PGOFFIO 8 /* offsetof(struct machine_desc, io_pg_offst)	@ */

#define PROC_INFO_SZ 52 /* sizeof(struct proc_info_list)	@ */
#define PROCINFO_INITFUNC 16 /* offsetof(struct proc_info_list, __cpu_flush)	@ */
#define PROCINFO_MM_MMUFLAGS 8 /* offsetof(struct proc_info_list, __cpu_mm_mmu_flags)	@ */
#define PROCINFO_IO_MMUFLAGS 12 /* offsetof(struct proc_info_list, __cpu_io_mmu_flags)	@ */
#define PBE_ADDRESS 0 /* offsetof(struct pbe, address)	@ */
#define PBE_ORIN_ADDRESS 4 /* offsetof(struct pbe, orig_address)	@ */
#define PBE_NEXT 8 /* offsetof(struct pbe, next)	@ */
#define SWSUSP_CPU 0 /* offsetof(struct swsusp_arch_regs, cpu_context)	@ */
#define SWSUSP_FPSTATE 104 /* offsetof(struct swsusp_arch_regs, fpstate)	@ */

#endif
