# SEP Platform Support
snd-soc-sep0611-objs := sep0611-pcm.o sep0611-i2s.o i2s_dma.o

obj-$(CONFIG_SND_SEP0611_SOC) += snd-soc-sep0611.o
#obj-$(CONFIG_CODEC_WM8976) += sep0611_wm8976.o wm8976.o
obj-$(CONFIG_CODEC_CS3700) += sep0611_cs3700.o cs3700.o
