#ifndef _SEP0611_REG_H_
#define _SEP0611_REG_H_

#define    UART0_BASE               0xB1000000
#define    GPIO_BASE                0xB0006000
#define    NAND_BASE                0xB2021000

#ifdef GPIO_BASE
// GPIO_BASE 0xB0006000
#define    GPIO_DBCLK               (GPIO_BASE + 0x000)

#define    GPIO_PORTA_DIR           (GPIO_BASE + 0x010)
#define    GPIO_PORTA_SEL           (GPIO_BASE + 0x014)
#define    GPIO_PORTA_DATA          (GPIO_BASE + 0x018)
#define    GPIO_PORTA_INTSEL        (GPIO_BASE + 0x01C)
#define    GPIO_PORTA_INTLEL        (GPIO_BASE + 0x020)
#define    GPIO_PORTA_INTPOL        (GPIO_BASE + 0x024)
#define    GPIO_PORTA_INTCLR        (GPIO_BASE + 0x028)
#define    GPIO_PORTA_SECFUN        (GPIO_BASE + 0x02C)

#define    GPIO_PORTB_DIR           (GPIO_BASE + 0x030)
#define    GPIO_PORTB_SEL           (GPIO_BASE + 0x034)
#define    GPIO_PORTB_DATA          (GPIO_BASE + 0x038)
#define    GPIO_PORTB_INTSEL        (GPIO_BASE + 0x03C)
#define    GPIO_PORTB_INTLEL        (GPIO_BASE + 0x040)
#define    GPIO_PORTB_INTPOL        (GPIO_BASE + 0x044)
#define    GPIO_PORTB_INTCLR        (GPIO_BASE + 0x048)
#define    GPIO_PORTB_SECFUN        (GPIO_BASE + 0x04C)

#define    GPIO_PORTC_DIR           (GPIO_BASE + 0x050)
#define    GPIO_PORTC_SEL           (GPIO_BASE + 0x054)
#define    GPIO_PORTC_DATA          (GPIO_BASE + 0x058)
#define    GPIO_PORTC_INTSEL        (GPIO_BASE + 0x05C)
#define    GPIO_PORTC_INTLEL        (GPIO_BASE + 0x060)
#define    GPIO_PORTC_INTPOL        (GPIO_BASE + 0x064)
#define    GPIO_PORTC_INTCLR        (GPIO_BASE + 0x068)
#define    GPIO_PORTC_SECFUN        (GPIO_BASE + 0x06C)

#define    GPIO_PORTD_DIR           (GPIO_BASE + 0x070)
#define    GPIO_PORTD_SEL           (GPIO_BASE + 0x074)
#define    GPIO_PORTD_DATA          (GPIO_BASE + 0x078)
#define    GPIO_PORTD_INTSEL        (GPIO_BASE + 0x07C)
#define    GPIO_PORTD_INTLEL        (GPIO_BASE + 0x080)
#define    GPIO_PORTD_INTPOL        (GPIO_BASE + 0x084)
#define    GPIO_PORTD_INTCLR        (GPIO_BASE + 0x088)
#define    GPIO_PORTD_SECFUN        (GPIO_BASE + 0x08C)

#define    GPIO_PORTE_DIR           (GPIO_BASE + 0x090)
#define    GPIO_PORTE_SEL           (GPIO_BASE + 0x094)
#define    GPIO_PORTE_DATA          (GPIO_BASE + 0x098)
#define    GPIO_PORTE_INTSEL        (GPIO_BASE + 0x09C)
#define    GPIO_PORTE_INTLEL        (GPIO_BASE + 0x0A0)
#define    GPIO_PORTE_INTPOL        (GPIO_BASE + 0x0A4)
#define    GPIO_PORTE_INTCLR        (GPIO_BASE + 0x0A8)
#define    GPIO_PORTE_SECFUN        (GPIO_BASE + 0x0AC)

#define    GPIO_PORTF_DIR           (GPIO_BASE + 0x0B0)
#define    GPIO_PORTF_SEL           (GPIO_BASE + 0x0B4)
#define    GPIO_PORTF_DATA          (GPIO_BASE + 0x0B8)
#define    GPIO_PORTF_INTSEL        (GPIO_BASE + 0x0BC)
#define    GPIO_PORTF_INTLEL        (GPIO_BASE + 0x0C0)
#define    GPIO_PORTF_INTPOL        (GPIO_BASE + 0x0C4)
#define    GPIO_PORTF_INTCLR        (GPIO_BASE + 0x0C8)
#define    GPIO_PORTF_SECFUN        (GPIO_BASE + 0x0CC)

#define    GPIO_PORTG_DIR           (GPIO_BASE + 0x0D0)
#define    GPIO_PORTG_SEL           (GPIO_BASE + 0x0D4)
#define    GPIO_PORTG_DATA          (GPIO_BASE + 0x0D8)
#define    GPIO_PORTG_INTSEL        (GPIO_BASE + 0x0DC)
#define    GPIO_PORTG_INTLEL        (GPIO_BASE + 0x0E0)
#define    GPIO_PORTG_INTPOL        (GPIO_BASE + 0x0E4)
#define    GPIO_PORTG_INTCLR        (GPIO_BASE + 0x0E8)
#define    GPIO_PORTG_SECFUN        (GPIO_BASE + 0x0EC)

#define    GPIO_PORTH_DIR           (GPIO_BASE + 0x0F0)
#define    GPIO_PORTH_SEL           (GPIO_BASE + 0x0F4)
#define    GPIO_PORTH_DATA          (GPIO_BASE + 0x0F8)
#define    GPIO_PORTH_INTSEL        (GPIO_BASE + 0x0FC)
#define    GPIO_PORTH_INTLEL        (GPIO_BASE + 0x100)
#define    GPIO_PORTH_INTPOL        (GPIO_BASE + 0x104)
#define    GPIO_PORTH_INTCLR        (GPIO_BASE + 0x108)
#define    GPIO_PORTH_SECFUN        (GPIO_BASE + 0x10C)

#define    GPIO_PORTI_DIR           (GPIO_BASE + 0x110)
#define    GPIO_PORTI_SEL           (GPIO_BASE + 0x114)
#define    GPIO_PORTI_DATA          (GPIO_BASE + 0x118)
#define    GPIO_PORTI_INTSEL        (GPIO_BASE + 0x11C)
#define    GPIO_PORTI_INTLEL        (GPIO_BASE + 0x120)
#define    GPIO_PORTI_INTPOL        (GPIO_BASE + 0x124)
#define    GPIO_PORTI_INTCLR        (GPIO_BASE + 0x128)
#define    GPIO_PORTI_SECFUN        (GPIO_BASE + 0x12C) 
#endif	//GPIO_BASE

#ifdef UART0_BASE
//UART0_BASE 0xB1001000
#define    UART0_DLBL               (UART0_BASE + 0x000)
#define    UART0_RXFIFO             (UART0_BASE + 0x000)
#define    UART0_TXFIFO             (UART0_BASE + 0x000)
#define    UART0_DLBH               (UART0_BASE + 0x004)
#define    UART0_IER                (UART0_BASE + 0x004)
#define    UART0_IIR                (UART0_BASE + 0x008)
#define    UART0_FCR                (UART0_BASE + 0x008)
#define    UART0_LCR                (UART0_BASE + 0x00C)
#define    UART0_MCR                (UART0_BASE + 0x010)
#define    UART0_LSR                (UART0_BASE + 0x014)
#define    UART0_MSR                (UART0_BASE + 0x018)
#endif // UART0_BASE

#ifdef NAND_BASE
//NAND_BASE 0xB2021000
#define    NAND_CFG                 (NAND_BASE + 0x000)
#define    NAND_CMD                 (NAND_BASE + 0x004)
#define    NAND_ADDR                (NAND_BASE + 0x008)
#define    NAND_SDATA               (NAND_BASE + 0x00C)
#define    NAND_CTRL                (NAND_BASE + 0x010)
#define    NAND_INIT                (NAND_BASE + 0x014)
#define    NAND_DMA                 (NAND_BASE + 0x018)
#define    NAND_STATUS              (NAND_BASE + 0x01C)
#define    NAND_ECC_PARITY0         (NAND_BASE + 0x020)
#define    NAND_ECC_PARITY1         (NAND_BASE + 0x024)
#define    NAND_ECC_PARITY2         (NAND_BASE + 0x028)
#define    NAND_ECC_PARITY3         (NAND_BASE + 0x02C)
#define    NAND_ECC_PARITY4         (NAND_BASE + 0x030)
#define    NAND_ECC_PARITY5         (NAND_BASE + 0x034)
#define    NAND_ECC_PARITY6         (NAND_BASE + 0x038)
#define    NAND_ECC_PARITY7         (NAND_BASE + 0x03C)
#define    NAND_ECC_PARITY8         (NAND_BASE + 0x040)
#define    NAND_ECC_PARITY9         (NAND_BASE + 0x044)
#define    NAND_ECC_PARITY10        (NAND_BASE + 0x048)
#define    NAND_ECC_PARITY11        (NAND_BASE + 0x04C)
#define    NAND_ECC_PARITY12        (NAND_BASE + 0x050)
#define    NAND_ECC_PARITY13        (NAND_BASE + 0x054)
#define    NAND_ERR_ADDR0           (NAND_BASE + 0x058)
#define    NAND_ERR_ADDR1           (NAND_BASE + 0x05C)
#define    NAND_ERR_ADDR2           (NAND_BASE + 0x060)
#define    NAND_ERR_ADDR3           (NAND_BASE + 0x064)
#define    NAND_ERR_ADDR4           (NAND_BASE + 0x068)
#define    NAND_ERR_ADDR5           (NAND_BASE + 0x06C)
#define    NAND_ERR_ADDR6           (NAND_BASE + 0x070)
#define    NAND_ERR_ADDR7           (NAND_BASE + 0x074)
#define    NAND_ERR_ADDR8           (NAND_BASE + 0x078)
#define    NAND_ERR_ADDR9           (NAND_BASE + 0x07C)
#define    NAND_ERR_ADDR10          (NAND_BASE + 0x080)
#define    NAND_ERR_ADDR11          (NAND_BASE + 0x084)
#define    NAND_ERR_ADDR12          (NAND_BASE + 0x088)
#define    NAND_ERR_ADDR13          (NAND_BASE + 0x08C)
#define    NAND_ERR_ADDR14          (NAND_BASE + 0x090)
#define    NAND_ERR_ADDR15          (NAND_BASE + 0x094)
#define    NAND_ERR_ADDR16          (NAND_BASE + 0x098)
#define    NAND_ERR_ADDR17          (NAND_BASE + 0x09C)
#define    NAND_ERR_ADDR18          (NAND_BASE + 0x0A0)
#define    NAND_ERR_ADDR19          (NAND_BASE + 0x0A4)
#define    NAND_ERR_ADDR20          (NAND_BASE + 0x0A8)
#define    NAND_ERR_ADDR21          (NAND_BASE + 0x0AC)
#define    NAND_ERR_ADDR22          (NAND_BASE + 0x0B0)
#define    NAND_ERR_ADDR23          (NAND_BASE + 0x0B4)
#define    NAND_ERR_ADDR24          (NAND_BASE + 0x0B8)
#define    NAND_ERR_ADDR25          (NAND_BASE + 0x0BC)
#define    NAND_ERR_ADDR26          (NAND_BASE + 0x0C0)
#define    NAND_ERR_ADDR27          (NAND_BASE + 0x0C4)
#define    NAND_ERR_ADDR28          (NAND_BASE + 0x0C8)
#define    NAND_ERR_ADDR29          (NAND_BASE + 0x0CC)
#define    NAND_FDATA               (NAND_BASE + 0x100)
#endif	//NAND_BASE

#endif //_SEP0611_REG_H_
